# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Downloading Geekbench 5
      run: |
        wget http://cdn.geekbench.com/Geekbench-5.1.0-Linux.tar.gz

    - name: Extracting the package
      run: |
        tar xvf Geekbench-5.1.0-Linux.tar.gz


    - name: Run the benchmark
      run: |
        cd Geekbench-5.1.0-Linux/
        chmod +x geekbench5        
        ./geekbench5
        

